name: Aggiornamento Punti FantaHitball

on:
  schedule:
    # Si attiva ogni ora al minuto 0, dalle 06:00 alle 22:00 UTC
    # In Italia corrisponde a: ogni ora dalle 07:00 alle 23:00 (o 08:00-00:00)
    - cron: '0 6-22 * * *'
  workflow_dispatch: # Permette di avviarlo a mano se hai fretta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica codice
        uses: actions/checkout@v3

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa librerie
        run: pip install -r requirements.txt

      - name: Esegui Scraper
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python scraper.py
