name: Aggiornamento Punti FantaHitball

on:
  schedule:
    # Esegue il bot alle 09:00, 18:00 e 00:00 italiane (ora legale)
    - cron: '0 7,16 * * *'
    
  workflow_dispatch: # Ti permette di farlo partire a mano cliccando su "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installazione librerie
        run: |
          pip install requests beautifulsoup4 firebase-admin

      - name: Riparazione e Pulizia JSON
        run: python -u ripara_json.py

      - name: Salva JSON corretto nel repository
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add giocatori.json
          git commit -m "Rimossi i due punti e pulite le squadre"
          git push
